### ISSUE TITLE
Prepare Diagnostics Bundle not working on ECE 2.9.0

### ISSUE THREAD

**Issue by andreaturli** [elastic/ansible-elastic-cloud-enterprise#119]
ECE Version Info
2.9.0
Bug description:
Prepare Diagnostics Bundle action returns immediately an Internal Server Error

Steps to reproduce:
Using an ECE=2.9.0, go to admin-console-elasticsearch deployment and try Prepare Diagnostics Bundle button from Operations

<img width="1287" alt="113317760-fb9b8d00-930f-11eb-9922-b88878c2bb1c" src="https://user-images.githubusercontent.com/222887/113330633-3eb12c80-931f-11eb-8646-b2bbac01d4b1.png">

Related to elastic/sdh-cloud#17745

**Comment by jguay** [comment]
Closing this issue - the permission issues in admin-console in 2.9.0 when generating log or diag zip file is not related to ansible role - at least in current form there is in fact no issue with the role
