### ISSUE TITLE
Pin containerd version to <=1.4.3-1 to avoid containers getting stuck in "Created" state

### ISSUE THREAD

**Issue by jakommo** [elastic/ansible-elastic-cloud-enterprise#121]
We've recently seen several occurrences of ECE users that had issue with containers getting stuck in "Created" state and traced it down to this upstream issue https://github.com/opencontainers/runc/pull/2871.

For now we should pin the containerd version to `<=1.4.3-1` to avoid that the affected `runc` gets used. 
As far as I can see, this would affect at least:
https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/c9f63f90f69e37d4499673f5cdb146262974a573/vars/os_CentOS_7.yml#L13
https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/c9f63f90f69e37d4499673f5cdb146262974a573/vars/os_Ubuntu_18.yml#L12 
https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/c9f63f90f69e37d4499673f5cdb146262974a573/vars/os_CentOS_8.yml#L13
https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/c9f63f90f69e37d4499673f5cdb146262974a573/vars/os_RedHat_8.yml#L13

Not sure about the others.

**Comment by obierlaire** [comment]
Fixed by https://github.com/elastic/ansible-elastic-cloud-enterprise/pull/125
