### ISSUE TITLE
Add support for Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by rhysxevans** [elastic/ansible-elastic-cloud-enterprise#13]
Hi

We are looking to deploy this, but we are currently standardising on Ubuntu 18.04, any chance of getting this supported in the ansible scripts ?

Thanks

**Comment by vaubarth** [comment]
Thanks for the issue, ECE is currently not officially supported on Ubuntu 18.04 (see "Elastic Cloud Enterprise" at https://www.elastic.co/de/support/matrix#matrix_os)
We will add support for it when ECE gets officially supported on Ubuntu 18.04 though.

**Comment by rhysxevans** [comment]
Hi

Thanks, is there an ETA for Ubuntu 18.04 support ?

Thanks

**Comment by vaubarth** [comment]
We are already tracking this but don't have an ETA yet, I will update this ticket when we do.

**Comment by andy-mcculloch** [comment]
Is there any update on when support for 18.04 will be coming?

**Comment by maxverro** [comment]
Can we expect the support of Ubuntu 18.04 this year? Ubuntu 16.04 already reached EOL. Packages will continue to receive security updates from Ubuntu until 2021. 

Any news on this would be appreciated.
