### ISSUE TITLE
On multiple runs "Create swap volume" failures

### ISSUE THREAD

**Issue by rhysxevans** [elastic/ansible-elastic-cloud-enterprise#14]
When running the ansible job multiple times, there is a failure on the "create swap volume" task. The following output is shown

```
TASK [elastic-cloud-enterprise : Create swap volume] 
******************************************************************************************************
fatal: [192.168.1.10]: FAILED! => {"changed": false, "msg": "Sorry, no shrinking of swap without force=yes."}
```

The server hardware has not been changed during runs.

Also if the proposed swap size is smaller than the current size, should this be run ?

Thanks

**Comment by vaubarth** [comment]
Skipping the step if the swap would shrink is probably the most sensible way to go about it.
