### ISSUE TITLE
Issue when "default user" has no authorized_keys set

### ISSUE THREAD

**Issue by rhysxevans** [elastic/ansible-elastic-cloud-enterprise#15]
Hi

This an issue in the  "Copy keys from default user to elastic user" task from the "tasks/system/general/make_user.yml" file. 

This issue occurs when the "standard" user (user running ansible) does not have any authorized_keys. 

Scenario is

1) We clone the machines from a standardised template, which has no ssh keys defined
2) We run the Elastic ansible role
3) We then run an ansible job to provision all the keys etc and delete the "standard" account, and a number of other internal base "build" configs

Would it not be better to allow the "authorized_keys" content to be defined in the ansible role ? Or at least not fail if no keys are defined ?

At the moment I am working around this with a separate task, that just essentially populates the "standard" users authorized_keys file prior to the make_user.yml running 

Thanks

**Comment by vaubarth** [comment]
You are right, there should be a way to specify those explicitly as well in the role.
