### ISSUE TITLE
docker image for ece 3.5.2 not available

### ISSUE THREAD

**Issue by l4r-s** [elastic/ansible-elastic-cloud-enterprise#174]
Hello,

The docker image for the current ece_version 3.5.2 (which is the default in this role) is not available on docker.elastic.co:

~~~
$ docker pull docker.elastic.co/cloud-enterprise/elastic-cloud-enterprise:3.5.2
Error response from daemon: manifest for docker.elastic.co/cloud-enterprise/elastic-cloud-enterprise:3.5.2 not found: manifest unknown: manifest unknown
~~~

**Comment by alpar-t** [comment]
Thanks for opening an issue @l4r-s. this was indeed off by one as the last version is 3.5.1 .  This is now fixed https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/master/defaults/main.yml#L3
