### ISSUE TITLE
Installing with ansible results in an invalid certificate

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ansible-elastic-cloud-enterprise#50]
## Problem
When using the ansible-playbook to install ece, results in an invalid (revoked) certificate, that modern browsers block, preventing you from using the UI 

Error is - 
NET::ERR_CERT_REVOKED 
(thus, the browser doesn't allow you to 'skip' and temporarily trust the certificate)

![image](https://user-images.githubusercontent.com/10343929/72845018-6a11a380-3ca6-11ea-8397-038f50e6b228.png)

## Tested on
2.4.0 / 2.4.3

## To recreate
Install ece on a remote host, by running the ansible-playbook from your local machine (might be a timezone issue? just a thought)

**Comment by vaubarth** [comment]
Interesting, however this sounds more like an installer issue since that is what is being invoked... will investigate
