### ISSUE TITLE
Add support for RHEL 7.x

### ISSUE THREAD

**Issue by zanbel** [elastic/ansible-elastic-cloud-enterprise#7]
This project is so great I'm already submitting a request to add support for RHEL :)
As ECE also support RHEL 7.x with RedHat Docker  1.13 it will be great if we can add that as another OS to the [vars](https://github.com/elastic/ansible-elastic-cloud-enterprise/tree/master/vars) folder.

**Comment by andrewpatroni** [comment]
CentOS7 and RHEL7 support has been added with PR #12
