### ISSUE TITLE
Update README regarding upgrade of ECE

### ISSUE THREAD

**Issue by selste** [elastic/ansible-elastic-cloud-enterprise#78]
Hi,
i tried an upgrade of a newly installed test environment and noticed that only providing '--skip-tags base' has a severe drawback:
It still triggers the tasks in 'direct-install' which result in a reboot of the node. In my case the docker containers weren't up and running fast enough afterwards and the upgrade terminated with an error along the lines
> Container frc-directors-director was not found -- does the current host have a role 'director'?

I haven't yet tried but i think using '--tags bootstrap' instead should be the correct way to do this.
Regards,

Steffen Elste

p.s.: Using '--tags bootstrap' did indeed work without any problems.

**Comment by obierlaire** [comment]
Hi @selste ! Yes, `--tags bootstrap` is the way to go. 
I'm closing this in favour of https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/74
