### ISSUE TITLE
"ece_version" Incorrect for Reference URI

### ISSUE THREAD

**Issue by zedtran** [elastic/ansible-elastic-cloud-enterprise#80]
https://github.com/elastic/ansible-elastic-cloud-enterprise/blob/19436e334f2d7ca8871d78479039a28e5a21a078/defaults/main.yml#L3

I believe this should be "2.5.1". Please advise.

**Comment by obierlaire** [comment]
Correct, even 2.6.1 now

**Comment by obierlaire** [comment]
Thanks @zedtran . Done with 2.6.1: https://github.com/elastic/ansible-elastic-cloud-enterprise/pull/93
