### ISSUE TITLE
Skip Tags setup_filesystem no longer works

### ISSUE THREAD

**Issue by aheys** [elastic/ansible-elastic-cloud-enterprise#82]
We have been using `--skip-tags setup_filesystem` when running this playbook, but after pulling in a more recent version, it seems the play is trying to create a volume for `xvdb`. Before, it would skip this section due to the tag being set to skip, but now it seems to try and create the volume anyway.

It appears that in #55 the included tasks `general/setup_xfs.yml` was moved to a new place and the tag `setup_filesystem` was not moved with it.

**Comment by alpar-t** [comment]
@obierlaire FYI
