### ISSUE TITLE
defaults/main.yml - Docker_Version "18.09"

### ISSUE THREAD

**Issue by user-987654321** [elastic/ansible-elastic-cloud-enterprise#86]
# General Elastic Cloud Enterprise relevant settings
ece_version: 2.4.3
ece_docker_registry: docker.elastic.co
ece_docker_repository: cloud-enterprise
docker_config: ""
ece_installer_url: "https://download.elastic.co/cloud/elastic-cloud-enterprise.sh"
ece_runner_id: "{{ ansible_default_ipv4.address }}"

# Overall setup variables (like package versions)
docker_version: "18.09"

Should docker_version now be
docker_version: "19.03"

**Comment by obierlaire** [comment]
Good point. I think we can close this in favour of https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/79 (the fix will include more default version changes as per https://github.com/elastic/ansible-elastic-cloud-enterprise/issues/79#issuecomment-697261907)
